package com.z.dao.mapper;

import com.z.bean.UseRecord;

public interface UseRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbggenerated Sun Oct 08 22:09:48 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbggenerated Sun Oct 08 22:09:48 CST 2017
     */
    int insert(UseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbggenerated Sun Oct 08 22:09:48 CST 2017
     */
    int insertSelective(UseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbggenerated Sun Oct 08 22:09:48 CST 2017
     */
    UseRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbggenerated Sun Oct 08 22:09:48 CST 2017
     */
    int updateByPrimaryKeySelective(UseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbggenerated Sun Oct 08 22:09:48 CST 2017
     */
    int updateByPrimaryKey(UseRecord record);
    

    int selectByStartTime(UseRecord record);
    
    UseRecord getUseRecord(UseRecord useRecord);
}