package com.z.dao.mapper;

import java.util.List;

import com.z.bean.Xia;

public interface XiaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xia
     *
     * @mbggenerated Tue Sep 12 16:10:36 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xia
     *
     * @mbggenerated Tue Sep 12 16:10:36 CST 2017
     */
    int insert(Xia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xia
     *
     * @mbggenerated Tue Sep 12 16:10:36 CST 2017
     */
    int insertSelective(Xia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xia
     *
     * @mbggenerated Tue Sep 12 16:10:36 CST 2017
     */
    Xia selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xia
     *
     * @mbggenerated Tue Sep 12 16:10:36 CST 2017
     */
    int updateByPrimaryKeySelective(Xia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xia
     *
     * @mbggenerated Tue Sep 12 16:10:36 CST 2017
     */
    int updateByPrimaryKey(Xia record);

    List<Xia> getAllEnableXia();
}